### ISSUE TITLE
TransactionObserver nil  when using with SwiftUI

### ISSUE THREAD

**Issue by jun1st** [groue/GRDBCombine#23]
Try using GRDBCombine with inside a SwiftUI view,

I start my observation inside my view model:
```
var spendingObserver: TransactionObserver?

init() {
    ....
    let observation = ValueObservation.tracking(value: { db in
                                try Outcome.fetchAll(db, sql: "select cost from outcome where date >= ?", arguments: [startOf15DaysAgo])
                            })
    self.spendingObserver =
            try! observation.start(in: databasePool, onChange: { outcomes in
                
                self.todayTotal =
                    outcomes.filter { (outcome) -> Bool in
                        outcome.date >= startOfToday
                    }.map({ (outcome) -> Double in
                        outcome.cost
                    }).reduce(0, +)
                
                self.yesterdayTotal =
                    outcomes.filter({ (outcome) -> Bool in
                            outcome.date < startOfToday && outcome.date >= (startOfToday - 1.days)
                    }).map({ (outcome) -> Double in
                        outcome.cost
                    }).reduce(0, +)
            })
    ...
}
```

use the viewmodel inside SwiftUI View.

```
 @ObservedObject var viewModel = UserSpendingViewModel()

 ...

SpendingSection(title: "Today", total: viewModel.todayTotal)
# it shows the data correctly

```

But when I try to insert a new record to database. It fails `ACCESS_BAD_ADDRESS`,  debug view shows as follows,  looks like it needs a strong reference?

<img width="434" alt="Screen Shot 2019-11-18 at 2 03 56 PM" src="https://user-images.githubusercontent.com/140474/69028255-5b8bdf00-0a0c-11ea-8632-b168d32bc957.png">

**Comment by groue** [comment]
Hello @jun1st,

If you are using Xcode 11.2, then set `DEAD_CODE_STRIPPING` to NO in the build settings of your app. This is a workaround for a Xcode bug, see https://github.com/groue/GRDB.swift/issues/640#issuecomment-548975256.

**Comment by jun1st** [comment]
@groue set `DEAD_CODE_STRIPPING` to `No` fix the issue.

thanks for the quick response and the awesome GRDB library  👍 👍
