### ISSUE TITLE
Crash with Xcode 11.2

### ISSUE THREAD

**Issue by danieleprice123** [groue/GRDBCombine#24]
With latest Xcode Build 11.2.1 (11B500), GRDB Demo throws Thread 1: EXC_BAD_ACCESS (code=1, address=0x505d) under EncodableRecord.  Used iPhone or iPads in the simulator, same result.  Demo worked as expected on prior build of Xcode.

Attempting to write my own code (grdb 4.6.1, grdbCombine 0.7.0), and I'm new and confused, so unsure if the issue is my work or something else.  Similar code to the demo, throwing Thread 1: EXC_BAD_ACCESS (code=2, address=0x1091f623d) in DatabasePublishers.Value.receive

Please let me know if you require further information and thank you for your work.

**Comment by groue** [comment]
Hello @danieleprice12,,

Set `DEAD_CODE_STRIPPING` to NO in the build settings of your app. This is a workaround for a Xcode bug, see https://github.com/groue/GRDB.swift/issues/640#issuecomment-548975256.

**Comment by groue** [comment]
Fixed with Xcode 11.3
