### ISSUE TITLE
Is sink() preferred over assign()?

### ISSUE THREAD

**Issue by simensol** [groue/GRDBCombine#39]
In all the examples in the documentation, the [sink()](https://heckj.github.io/swiftui-notes/#reference-sink) subscriber is used. For example:

```
let cancellable = publisher.sink(
    receiveCompletion: { completion in ... },
    receiveValue: { (players: [Player]) in
        print("Fresh players: \(players)")
    })
```

Are there any reasons we should not use [assign()](https://heckj.github.io/swiftui-notes/#reference-assign) with GRDBCombine?

**Comment by groue** [comment]
Hello again @simensol,

GRDBCombine publishers are regular Combine publishers, and they can feed any Combine Subscriber. You can dump them into `sink`, `assign`, and process them in any possible way.

So one can argue that all the `sink` examples in the documentation are unnecessary. And even, as your question reveals, *confusing*.

I'll try to find a better balance in the way documentation is written. Until then, please dump those publishers wherever you want to :-)

**Comment by simensol** [comment]
Alright, thanks for answering (again)! And thanks for making this fabulous package!

**Comment by groue** [comment]
You're welcome! We're all learning about Combine :-)
