### ISSUE TITLE
Type 'Publishers' has no member 'Just'; did you mean 'Last'?

### ISSUE THREAD

**Issue by adamek314** [groue/GRDBCombine#5]
One error showing up in Publisher+Result.swift.

This worked in iOS13 beta 2 and xCode 11 beta 2. The error shows up in beta 3.

**Comment by groue** [comment]
Hello @adamek314,

Thanks for the report. I hope #6 fixes your issue until I can take care of updating the library, at the end of July.

**Comment by groue** [comment]
Now see #7 for Xcode 11 beta 4.

**Comment by groue** [comment]
Version 0.3.0 has shipped, with support for Xcode 11 beta 4.
